### ISSUE TITLE
Support for Credential Manifest data model

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/wallet#1392] opened 2022-01-05 19:48 UTC
- [ ] proposing in universal wallet
- [ ] implementation in aries
- [ ] implementation in agent SDK
- [ ] wallet JS SDK tests
- [ ] taking priority over credential display data (design + implementation for fallback strategy)
- [ ] wallet UI changes to use credential manifest

**Comment by rolsonquadras** [comment] 2022-01-17 19:25
This is a duplicate of https://github.com/trustbloc/wallet/issues/1398

**Closed by rolsonquadras** 2022-01-17 19:25 UTC
Labels: type: enhancement
