### ISSUE TITLE
[Credential Manifest] Wallet - Using credential manifest APIs

### ISSUE THREAD

**Issue by sudeshrshetty** [trustbloc/wallet#1424] opened 2022-01-17 19:09 UTC
credential manifest support in credential preview (wallet credentials screen, save, share credentials)

**Comment by sudeshrshetty** [comment] 2022-01-25 04:38
https://github.com/trustbloc/wallet/issues/1462

**Comment by rolsonquadras** [comment] 2022-02-22 18:14
This is a duplicate of #1462

**Closed by rolsonquadras** 2022-02-22 18:14 UTC
